spring.application.name=marcacion-personal
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=${DB_URL:jdbc:postgresql://127.0.0.1:5432/marcacion_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.open-in-view=false
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

security.jwt.secret=${JWT_SECRET:EstaEsUnaClaveSecretaMuyLargaParaDesarrolloLocalCambiarEnProduccion2026}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

minio.url=${MINIO_URL:http://127.0.0.1:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket=${MINIO_BUCKET:evidencias-marcaciones}

app.seed.enabled=${APP_SEED_ENABLED:false}
app.processing.enabled=${APP_PROCESSING_ENABLED:true}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://127.0.0.1:5500,http://localhost:5500,http://127.0.0.1:5173,http://localhost:5173}
