spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:marcacion_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Deshabilitar para que solo se pueda acceder desde tu propia máquina por seguridad
spring.h2.console.settings.web-allow-others=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

minio.url=http://127.0.0.1:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=evidencias-marcaciones
# Aumentar límite de tamaño para subida de fotos binarias
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
